/*
 * ConnectWnd.java
 *
 * Created on 2 Сентябрь 2008 г., 0:03
 */

package pathanmssql2kmng;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;                  // JDBC package
import javax.sql.*;                 // extended JDBC package
import com.microsoft.sqlserver.jdbc.*;

//import com.inet.tds.*;
//import com.inet.pool.*;
/**
 *
 * @author  uas
 */
public class ConnectWnd extends javax.swing.JInternalFrame {
    
    /** Creates new form ConnectWnd */
    public ConnectWnd(JFrame frame) {
        initComponents();
        jframe=(MainWnd) frame;
        setLocation((jframe.screenSize.width-getWidth())/2 , (jframe.screenSize.height-getHeight())/2 );
        jLabel1.setText("\u0418\u043c\u044f \u0445\u043e\u0441\u0442\u0430/\u0441\u0435\u0440\u0432\u0435\u0440\u0430:");
        jLabel2.setText("\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f:");
        jLabel3.setText("\u041f\u0430\u0440\u043e\u043b\u044c:");
        jBtnCancel.setText("\u041e\u0442\u043c\u0435\u043d\u0430");
        setTitle("\u0421\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435 \u0441 MS SQL 2K Server...");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtConnStr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordUser = new javax.swing.JPasswordField();
        jBtnOk = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTxtConnStr.setText("localhost");
        jPanel1.add(jTxtConnStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 190, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTxtUsername.setText("sa");
        jPanel1.add(jTxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPasswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordUserActionPerformed(evt);
            }
        });

        jPanel1.add(jPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 190, -1));

        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jPanel1.add(jBtnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 30));

        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jPanel1.add(jBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, 30));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
    // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
    // TODO add your handling code here:
        try{
            if(jframe.SQLConnect!=null){
                JOptionPane.showMessageDialog(null, "Please disconnect server select menu.", "Connection Failure", JOptionPane.INFORMATION_MESSAGE);
            }
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver").newInstance();
            DriverManager.registerDriver(new com.microsoft.sqlserver.jdbc.SQLServerDriver());
            DriverManager.setLoginTimeout(1000);
            
            jframe.login=jTxtUsername.getText();
            jframe.password=jPasswordUser.getText();
            jframe.urlConnectFull= jTxtConnStr.getText();
            //jframe.SQLConnect= DriverManager.getConnection("jdbc:microsoft:sqlserver://"+jframe.urlConnectFull+":1433","User="+jframe.login,"Password="+jframe.password);
            jframe.SQLConnect= DriverManager.getConnection("jdbc:sqlserver://"+jframe.urlConnectFull+":1433;Databasename=master",jframe.login,jframe.password);
            jframe.conMD = jframe.SQLConnect.getMetaData();
	    //System.out.println("1. Driver Name:\t"    + jframe.conMD.getDriverName());
	    //System.out.println("2. Driver Version:\t" + jframe.conMD.getDriverVersion());
            jframe.ServerName= jTxtConnStr.getText();
            jframe.setTitle(jframe.getTitle()+"[Connect to "+jframe.ServerName+"]"  );
            
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, " " + e, "Connection Failure", JOptionPane.ERROR_MESSAGE);
          return;
        }
        
        setVisible(false);
        jframe.DBwnd.setVisible(true);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jPasswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordUserActionPerformed
// TODO add your handling code here
        setVisible(false);
    }//GEN-LAST:event_jPasswordUserActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
// TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosed
    
        private MainWnd jframe;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordUser;
    private javax.swing.JTextField jTxtConnStr;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables
    
}
