/*
 * ConsoleFrame.java
 *
 * Created on 2 Сентябрь 2008 г., 10:53
 */

package pathanmssql2kmng;
import javax.swing.*;
import java.util.Vector;
import java.util.*;

import java.sql.*;                  // JDBC package
import javax.sql.*;                 // extended JDBC package
import com.microsoft.sqlserver.jdbc.*;
//import com.inet.tds.*;
//import com.inet.pool.*;

/**
 *
 * @author  uas
 */
public class ConsoleFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form ConsoleFrame */
    public ConsoleFrame(JFrame frame) {
        initComponents();
        jframe= (MainWnd) frame;
        setLocation((jframe.screenSize.width-getWidth()-300) , (50) );
        setTitle("SQL Console...");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnStart = new javax.swing.JButton();
        jBtnStop = new javax.swing.JButton();
        jcbDatabase = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jBtnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/png/20px_green_right.png")));
        jBtnStart.setToolTipText("Start the SQL script");
        jBtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtnStart);

        jBtnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/png/20px_icon_delete.png")));
        jBtnStop.setToolTipText("Stop running script");
        jToolBar1.add(jBtnStop);

        jToolBar1.add(jcbDatabase);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier", 0, 12));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
        setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosed

    private void jBtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartActionPerformed
        // TODO add your handling code here:
            try{
              if(jframe.SQLConnect.isClosed())
                jframe.SQLConnect= DriverManager.getConnection("jdbc:sqlserver://"+jframe.urlConnectFull+":1433;Databasename=master",jframe.login,jframe.password);
            }catch(Exception e){
              JOptionPane.showMessageDialog(null, " " + e, "Error", JOptionPane.ERROR_MESSAGE);              
            }
        

        setTitle("SQL Console...");
        if(jTextArea1.getText().equals("")) return;
        try{
         jframe.SQLConnect.setCatalog( (String)jcbDatabase.getSelectedItem() );
         Statement st3 = jframe.SQLConnect.createStatement();
         StringTokenizer strToken= new StringTokenizer(jTextArea1.getText());
         boolean select=false;
         
         while(strToken.hasMoreTokens()){
             String strFirstTok=strToken.nextToken();
             if(strFirstTok.equals("select")||strFirstTok.equals("SELECT")){
                 select=true;
                 break;
             }else select=false;
         }
       //jTextArea1.ge  
       if(select) {
          ResultSet rs1 = st3.executeQuery(jTextArea1.getText());
         
         if(rs1.getMetaData().getColumnCount()>=0){
           String[] headers=new String[rs1.getMetaData().getColumnCount()];
           ArrayList Datatables= new ArrayList();
            for(int j=1; j<=rs1.getMetaData().getColumnCount(); j++){
                    headers[j-1]= rs1.getMetaData().getColumnName(j);
            }
           
           while (rs1.next()){
             String[] columns= new String[rs1.getMetaData().getColumnCount()];
                for(int j=1; j<=rs1.getMetaData().getColumnCount(); j++){
                    columns[j-1]= rs1.getString(j);
                }
                Datatables.add(columns);
           }
           
           Tableswnd tableswnd= new Tableswnd(Datatables, headers);
           tableswnd.setTitle((String)jcbDatabase.getSelectedItem()+" "+rs1.getMetaData().getTableName(1)); 
           jframe.mainwnddesktop.add(tableswnd);
           tableswnd.setVisible(true);
         }
        }else{
            st3.execute(jTextArea1.getText());
            setTitle("SQL Console... Ok");
        }
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " " + e, "Not run the script", JOptionPane.ERROR_MESSAGE);          
        }
       
    }//GEN-LAST:event_jBtnStartActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    // TODO add your handling code here:
        setTitle("SQL Console...");
        if(jframe.NameDatabase!=null){
         jcbDatabase.removeAllItems();   
           for(int j=0;j<jframe.NameDatabase.size(); j++){
             jcbDatabase.addItem(jframe.NameDatabase.elementAt(j));
           }
        }  
        jTextArea1.setText("");
    }//GEN-LAST:event_formInternalFrameOpened
    private MainWnd jframe;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnStart;
    private javax.swing.JButton jBtnStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox jcbDatabase;
    // End of variables declaration//GEN-END:variables
    
}
