/*
 * InfoWnd.java
 *
 * Created on 6 Сентябрь 2008 г., 0:25
 */

package pathanmssql2kmng;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author  uas
 */
public class InfoWnd extends javax.swing.JInternalFrame {
    
    /** Creates new form InfoWnd */
    public InfoWnd(JFrame frame) {
        initComponents();
        jframe= (MainWnd)frame;
        jButton1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
             setVisible(false);   
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Info");
        jButton1.setText("Ok");

        jLabel1.setText("\u041e \u0441\u0435\u0431\u0435 \u043b\u044e\u0431\u0438\u043c\u043e\u043c...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 44, Short.MAX_VALUE)
                .add(jButton1)
                .add(19, 19, 19))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    protected MainWnd jframe=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
