/*
 * Tableswnd.java
 *
 * Created on 3 Сентябрь 2008 г., 12:46
 */

package pathanmssql2kmng;

import javax.swing.*;
import javax.swing.table.*;
import javax.swing.border.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author  uas
 */
public class Tableswnd extends javax.swing.JInternalFrame {
    
    /** Creates new form Tableswnd */
    public Tableswnd(ArrayList columns, String[] headers) {
        initComponents();
        
        QueryTableModel tablemodel= new QueryTableModel(headers, columns);

        maintables= new JTable(tablemodel);
        maintables.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        jScrollPane1.setViewportView(maintables);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private MainWnd jframe=null;
    private JTable maintables= null;
    


  public class QueryTableModel extends AbstractTableModel {
    ArrayList cache= null;
    String[] headers= null;

    public QueryTableModel(String[] headersName, ArrayList Tables) {
      cache = Tables;
      headers= new String[headersName.length];
      for(int in=0; in<headersName.length; in++)
          headers[in]= new String(headersName[in]);
    }

    public String getColumnName(int i) {
      return headers[i];
    }

    public int getColumnCount() {
      return headers.length;
    }

    public int getRowCount() {
      return cache.size();
    }

    public Object getValueAt(int row, int col) {
      return (Object)((String[]) cache.get(row))[col];
//      return ((String[]) cache.elementAt(col))[row];
    }

    public void setValueAt(Object aValue, int row, int col){
    };
    
  }
}

